runtime: python39

entrypoint: gunicorn -b :$PORT wsgi:app

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65
            
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto
