# fly.toml app configuration file generated for cfd on 2023-06-21T18:06:03+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cfd"
primary_region = "waw"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
